---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: flowspace-local
spec:
  encryptedData:
    admin-password: AgAMg7vZ6Eea1JHxyXaGBg7caucQrzxN5CszFE3vyk2i1EwMIoh3ZBWbypcUrXT/nIuInd4AnydtXftf8fWHZ7w4u7DiH7y5TRHuKDr9RTbH7lQThj+nYJp+OI2AJVhWQmkv6/Y/D7JFWluJGwfIX3nxXWKeAFEMoFBFlxFTqFnPvVt8uIgwHAt1MM25Xwtjf1l0ra0LqCZzifL9alJAaGlSrCzA3mysh5O7rbumJmOelEr2BO1Iq38lE3+rDRT/ek6Ypgh4/1uUBRqaZMnHbIog5ETAd6jegmhNCTuuINipSN86mX3XhIoIDXMKZNQaM7RKEHXXApIzddDhyRK/nV3Cubwdd0FyJ/Hh8ZPnaEZ5inp+rcU3oQDl7++uyf2vK+fLDBuGI/7dubA7n0S6RS/EKK+j16mcMrGxIWs0DAmwFA8ARzHqWpBUsx7dDQwsmPRNG/GYRXZ8TP2LYIqkdNNVPopG1Hs4tATjbeEX9/KnzJuvbGVibD8BZnwUyiJd6iaBm+nGvOHtC41yGpyYgomIdS00KNqm6WI6Ar8vhTkYp0iuhGfLOK7zjTQeqpJnicWTD1N8jdgY+/YQLOnL709ko+WXKqf3znDy7tHc/Pz5BRE8kYXk7ye0M9UtMCOz8lOOUdokpZSvVx43Xl3EveWb6DHJc382uoljozSRTseTlmuVCf+kaMPtbhKhNLzxd0Lnu0KRJmuLBDV4aFOjVzcDhcOPGMzWsafkpLWiZ1FJmd+tLK5ltogX3uOlo1R045o+AGNLM0t3o2txpZJJm5x+
    admin-user: AgA/c6C8pYl3ATdVOC31Lc9dIblF9RpESZxMr/jO5XV96ojtMfBezV2tODb6rJvy8+mHC/o8e42wxpAVO7QDlo6+E/laA83e0MasufUEv+Qa+s6b8mQv+ibsUDBoc/UnmtxYxklEElNYQYVhgI/eo2BPCBZ37eyXE4gzZBAr7OfejlHMi8KuIt+ci00DJPl4ARaLzk5sz8UgjyBfFVLjVROICKHbWVSbku4Jk0Ca33tE9tlwCJBuloEgZMf+hOYyyhNISVp+/MZ6G4H7tu0khVW1CMCFlPANLCX1EvSItdcImKt86DL6W3VH8149QA7rfXp+OqY+G9duU6pTlGvMMruNERMhSipa6hQ3nx1N3bR9nWzTIzlKk0SK4i1YcBWupN3wv19bfvCvX2uMgrOcZCZCzpe1oADW6zDOcy8hMWgQOASAtZZmnG+BymzMXGmgBzV5C3DPQTt9FLVa7RvhSPTvQH1uHq0sNqaleY4febGyWeywL5PDhhkeuHOM4wVxYqt9RUfu4QGfTFegOm8MGNHhwfilxDxo8KDZs8pbNnJfCK5ZiAjkyKbcG7qb4GsrKZ//3QeAJZuT1nZdOvhkeI+svKz98bud05M1ThpFzPhSTJngN9J/eRzAInvHU1a8zL4C8fsBflmXTo8wiION4EGDtuFnBw2hX99iiVMhJY2ZzjuHFbnZ65ifgy7Wzd3vRiVqevWXFA==
  template:
    metadata:
      name: grafana-admin
      namespace: flowspace-local
