apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowspace-local
resources:
  - ../../../base/workspace
  - namespace.yaml
  - postgres.yaml
configMapGenerator:
  - name: workspace-config
    literals:
      - ENVIRONMENT=local
      - HTTP_ADDR=:8080
      - OIDC_AUDIENCE=workspace-api
      - OIDC_DISCOVERY_URL=http://keycloak-http/auth/realms/flowspace
      - OIDC_ISSUER=http://localhost:8080/auth/realms/flowspace
      - PGDATABASE=workspace
      - PGHOST=workspace-postgres
      - PGPORT=5432
      - PGSSLMODE=disable
      - PGUSER=workspace
generatorOptions:
  disableNameSuffixHash: true
