apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowspace-local
resources:
  - ../../../base/workspace
  - namespace.yaml
  - postgres.yaml
  - session-tls-sealed-secret.yaml
configMapGenerator:
  - name: workspace-config
    literals:
      - ENVIRONMENT=local
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=1.0
      - HTTP_ADDR=:8080
      - IDENTITY_JWKS_URL=http://identity-internal:8081/.well-known/jwks.json
      - IDENTITY_ISSUER=urn:flowspace:identity:local
      - IDENTITY_AUDIENCE=flowspace-api
      - IDENTITY_SESSION_ADDR=identity-session:8082
      - IDENTITY_SESSION_SERVER_NAME=identity-session.flowspace-local.svc
      - IDENTITY_CLIENT_CERT_FILE=/keys/session/tls.crt
      - IDENTITY_CLIENT_KEY_FILE=/keys/session/tls.key
      - IDENTITY_CA_FILE=/keys/session/ca.crt
      - PGDATABASE=workspace
      - PGHOST=workspace-postgres
      - PGPORT=5432
      - PGSSLMODE=disable
      - PGUSER=workspace
generatorOptions:
  disableNameSuffixHash: true
