apiVersion: batch/v1
kind: Job
metadata:
  name: workspace-migrate
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workspace-migrate
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      securityContext:
        fsGroup: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: workspace-migrate
          image: flowspace/workspace-api
          command:
            - /workspace-migrate
          envFrom:
            - configMapRef:
                name: workspace-config
            - secretRef:
                name: workspace-database
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
